compliments = ["You look great today.",
"Your smile is contagious.",
"You're a smart cookie.",
"I bet you make babies smile.",
"You have impeccable manners.",
"I like your style.",
"You have the best laugh.",
"I appreciate you.",
"You are the most perfect you there is.",
"Your perspective is refreshing.",
"You're an awesome friend.",
"You deserve a hug right now.",
"You should be proud of yourself.",
"You're more helpful than you realize.",
"You have a great sense of humor.",
"Is that your picture next to 'charming' in the dictionary?",
"Your kindness is a balm to all who encounter it.",
"On a scale from 1 to 10, you're an 11.",
"You're even more beautiful on the inside than you are on the outside.",
"Your eyes are breathtaking.",
"You are making a difference.",
"You're like sunshine on a rainy day.",
"Your ability to recall random factoids at just the right time is impressive.",
"You're a great listener.",
"How is it that you always look great, even in sweatpants?",
"Everything would be better if more people were like you!",
"That color is perfect on you.",
"You always know -- and say -- exactly what I need to hear when I need to hear it.",
"You smell really good.",
"Being around you makes everything better!",
"When you're not afraid to be yourself is when you're most incredible.",
"You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
"You're wonderful.",
"Jokes are funnier when you tell them.",
"You're better than a triple-scoop ice cream cone. With sprinkles.",
"Your hair looks stunning.",
"You're one of a kind!",
"You're inspiring.",
"Our community is better because you're in it.",
"You have the best ideas.",
"You always know how to find that silver lining.",
"Everyone gets knocked down sometimes, but you always get back up and keep going.",
"You're a candle in the darkness.",
"You're a great example to others.",
"Being around you is like being on a happy little vacation.",
"You always know just what to say.",
"You're always learning new things and trying to better yourself, which is awesome.",
"You're more fun than bubble wrap.",
"You're great at figuring stuff out.",
"Your voice is magnificent.",
"The people you love are lucky to have you in their lives.",
"You're like a breath of fresh air.",
"You're so thoughtful.",
"Your creative potential seems limitless.",
"Somehow you make time stop and fly at the same time.",
"Any team would be lucky to have you on it.",
"In high school I bet you were voted 'most likely to keep being awesome.'"
"I bet you do the crossword puzzle in ink.",
"If you were a scented candle they'd call it Perfectly Imperfect (and it would smell like summer).",
"There's ordinary, and then there's you",
"You're someone's reason to smile.",
"You're even better than a unicorn, because you're real.",
"How do you keep being so funny and making everyone laugh?",
"Has anyone ever told you that you have great posture?",
"The way you treasure your loved ones is incredible.",
"You're really something special.",
"You're a gift to those around you."]
