class insultslist():
    insults = ["If you spoke your mind, you'd be speechless.",
    "I'll never forget the first time we met, although I'll keep trying.",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "It's kinda sad watching you attempt to fit your entire vocabulary into a sentence.",
    "Your face makes onions cry.", "You're the reason they invented double doors!",
    "I wasn't born with enough middle fingers to let you know how I feel about you.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "You bring everyone a lot of joy, when you leave the room.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "If laughter is the best medicine, your face must be curing the world.",
    "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
    "How many times do I have to flush to get rid of you?",
    "The last time I saw a face like yours I fed it a banana.",
    "At least when I do a handstand my stomach doesn't hit me in the face.",
    "You have two brains cells, one is lost and the other is out looking for it.",
    "You must have been born on a highway, because that's where most accidents happen.",
    "It looks like your face caught on fire and someone tried to put it out with a fork",
    "You're so ugly Hello Kitty said goodbye to you.",
    "Your family tree is a cactus, because everybody on it is a prick.",
    "You are so ugly that when your mama dropped you off at school she got a fine for littering." ,
    "If you were twice as smart, you'd still be stupid.",
    "Your so ugly when you popped out the doctor said aww what a treasure and your mom said yeah lets bury it",
    "I would ask how old you are, but I know you can't count that high.",
    "If you really want to know about mistakes, you should ask your parents.",
    "I could eat a bowl of alphabet soup and crap out a smarter comeback than what you just said." ,
    "You have something on your chin...3rd one down.",
    "With a face like yours, I wish I was blind." ,
    "You're so fat you need cheat codes to play Wii Fit.",
    "Why don't you check up on eBay and see if they have a life for sale.",
    "Here's 20 cents, call all your friends and give me back the change.",
    "Your momma so fat, when she went to a doctor, she stepped on a scale and the doctor said 'Hey, that's my phone number.'",
    "I’d give you a nasty look but you’ve already got one.",
    "I love what you’ve done with your hair. How do you get it to come out of the nostrils like that?",
    "I’ve seen people like you before, but I had to pay admission.",
    "Scientists say the universe is made up of neutrons, protons and electrons. They forgot to mention morons.",
    "You’re so fat you could sell shade.",
    "Why is it acceptable for you to be an idiot but not for me to point it out?",
    "Did you know they used to be called “Jumpolines” until your mum jumped on one?",
    "Someday you’ll go far… and I hope you stay there.",
    "Stupidity’s not a crime, so you’re free to go.",
    "If I had a face like yours I’d sue my parents.",
    "Your doctor called with your colonoscopy results. Good news – they found your head.",
    "What’s the difference between your girlfriend and a walrus? One has a moustache and smells of fish and the other is a walrus.",
    "The zoo called. They’re wondering how you got out of your cage.",
    "I was hoping for a battle of wits but you appear to be unarmed."]

