slogans = ["Follow your {}.",
"{} know-how.",
"{} is what the world was waiting for.",
"Swing your {}.",
"{} - go for the game.",
"There is no life without {}.",
"{} lifestyle",
"Discover the world of {}.",
"No {}, no kiss.",
"{}, just the best.",
"{}rific.",
"My {} and me.",
"The secret of {}.",
"{} wanted.",
"{} - today and tomorrow.",
"Connect with {}.",
"{} - now!",
"I'd do anything for {}.",
"You better get inside {}.",
"{} for you!",
"{} - first class!",
"The Future of {}.",
"{} Dreamteam.",
"{} - simplified!",
"Always the real thing, always {}.",
"Feel the magic of {}.",
"Thanks {}.",
"{}, since 1845.",
"What is {}?",
"{} is my sport.",
"{} - it's like heaven!",
"It's your {}!",
"{} for the masses.",
"{} inside you.",
"Simply {}!",
"{} kicks ass.",
"{} - Just do it.",
"Free {}.",
"Oh my goddess, it's a {}.",
"See you at {}.",
"{} - a safe place in an unsafe world!",
"Anyone can handle {}.",
"{}'s got it all!",
"One goal, one passion - {}.",
"My {}, your {}, {} for all!",
"I wish i was a {}.",
"{} - be ready.",
"You better get your {} out.",
"You know when it's {}.",
"Things go better with {}.",
"Say it with {}.",
"The American Way of {}.",
"{} is better than chocolate.",
"{}, your family will love you.",
"Can you feel {}?",
"The queen buys {}.",
"Take what you want, but leave {} alone!",
"Everything is simple with {}.",
"Call a friend, call {}.",
"Praise {}.",
"Endless possibilities with {}.",
"{}. The power on your side.",
"{} is inspiration.",
"{} - spice up your life.",
"Go farther with {}.",
"{} loves you.",
"{} nonstop.",
"{} is the only way to be happy.",
"Truly {}.",
"{}, where success is at home.",
"{}. See more. Do more.",
"The Queen of {}.",
"{} is my world.",
"{}, created by nature.",
"It must be {}.",
"{} - Think different.",
"My {} is mine.",
"Easy {}.",
"{} - forget the rest.",
"{} - One name. One legend.",
"{} never die.",
"{} will be for you what you want it to be.",
"Make the world a better place with {}.",
"I want {} and I want it now.",
"{} for me!",
"{} brings out the best.",
"Live {}.",
"{}, so what!",
"Passion for {}.",
"I lost weight with {}.",
"Let's talk about {}.",
"The {} effect.",
"{}, the smart choice.",
"{}, in touch with tomorrow.",
"{} is my passion.",
"Make yourself at home with {}.",
"Where's {}?",
"Ooh la la, {}.",
"{}, this is it!",
"{}? Yes please.",
"Up, up and away with {}.",
"Be inspired by {}.",
"World's finest {}.",
"Made by {}.",
"The one and only {}.",
"{}, your specialist.",
"The {} spirit.",
"{} wonder.",
"For the love of {}.",
"{} - be prepared.",
"{} groove.",
"It's my {}!",
"{} is a female force.",
"{}, better than sex.",
"{}, the clever way.",
"{} - what more could you want?",
"{} empowers you.",
"Buy {} now!",
"My {} beats everything.",
"{} makes me hot.",
"{} is your safe place in an unsafe world!",
"Everyone should believe in {}.",
"{} values.",
"It's time to think about {}.",
"{} - If you love {}.",
"Don't play with fire, play with {}.",
"{}, whiter than the whitest!",
"{} keeps going, and going, and going...",
"The original {}.",
"{}, one for all.",
"{} - get ready.",
"{}, your way!",
"There's a bit of {} in all of us.",
"{} forever.",
"{}, you'll love it!",
"{} - a class of it's own",
"Who is {}?",
"Naughty little {}.",
"Think different, think {}.",
"Jesus loves {}.",
"You wouldn't want to miss {}.",
"{} is the best!",
"Bigger. Better. {}.",
"You can't stop {}.",
"{} will do anything for you.",
"The ideal {}.",
"{}, the original.",
"Lucky {}.",
"Have a break, have a {}.",
"The Power of {}.",
"You can't beat {}.",
"{} extra dry.",
"Go to heaven with {}.",
"{} - You see this name, you think dirty.",
"The best {} in the world.",
"Start the day with {}.",
"With a name like {}, it has to be good.",
"See the world with {}.",
"I wish i had a {}.",
"{} - The Revolution.",
"Nothing to worry about with {}.",
"{}, the secret of women.",
"{} after a long day.",
"Think {}.",
"I trust {}.",
"Nonstop {}.",
"I want more, I want {}.",
"{} - go for it!",
"Be alive with {}.",
"3...  2...  1... {}.",
"Where's your {}?",
"Every {} has a story.",
"{}'s like heaven.",
"{}, stay in touch.",
"{} takes good care of you.",
"{} for president.",
"{} is forever.",
"{}. We build smiles.",
"The {} people.",
"{}, you've got it!",
"{} - to feel free!",
"Heal the world with {}.",
"Stay cool with {}.",
"{} on the outside, tasty on the inside.",
"And on the eighth day, god created {}.",
"All you need is {}.",
"It's not a dream. {} is real!",
"Kick ass with {}!",
"Firstclass {}!",
"You don't want {} as your enemy!",
"{}. Making people sucessful in a changing world.",
"{} evolution.",
"{}, love it or leave it.",
"{} is a never ending story.",
"No need to worry with {}.",
"The Spirit of {}.",
"{}... whatever you want.",
"A day with {}.",
"{} - play it!",
"Life's beautiful with {}.",
"The gods made {}.",
"{} is good for you.",
"{} is the sound of the future.",
"{}, the real thing.",
"Oh my gods, it's a {}.",
"I quit smoking with {}.",
"{}, pure lust.",
"The {} universe.",
"{} for a better future.",
"Saved by {}!",
"{} - living innovation",
"Worldclass {}!",
"Keep going well, keep going {}.",
"Next stop, {}.",
"{} online.",
"Don't worry, {} takes care.",
"{}, the freshmaker.",
"I fall for {}.",
"Everyone loves {}.",
"{} is your friend.",
"My way is {}.",
"{} never sleeps.",
"{}? You bet.",
"The art of {}.",
"{}tastic!",
"Inspired by {}.",
"I wouldn't leave the house without {}.",
"{} strikes back.",
"I believe in {}.",
"{} makes dreams come true.",
"The wonder has a name: {}.",
"{} - enjoy the difference.",
"Don't mess with {}.",
"I'd sleep with {}.",
"{} can do.",
"{} - your game.",
"Break through with {}.",
"The magic of {}.",
"Where the hell is {}?",
"{}, it's as simple as that!",
"Feel good with {}.",
"Think. Feel. {}.",
"The {} look.",
"When you say {} you've said it all.",
"Don't get in the way of {}.",
"Share moments, share {}.",
"The president buys {}.",
"Don't forget your {}.",
"Play {}, start living.",
"Who wouldn't fight for {}?",
"Once {}, always {}.",
"Are you ready for {}?",
"Nobody does it like {}.",
"Let's {}!",
"Nobody doesn't like {}.",
"Way to go, {}!",
"Halleluja, it's a {}.",
"Enjoy {}.",
"{} - as good as it gets!",
"There's only one thing in the world I want and that is {}.",
"{} never lies.",
"Feel it - {}!",
"{} beat.",
"Do it with {}.",
"I can't believe it's {}.",
"{} for a professional image.",
"{} only.",
"Be part of {}.",
"High life with {}.",
"{} innovate your world.",
"{} for your health.",
"Say {}.",
"Long life {}.",
"Good to know {}.",
"{}, i want it all.",
"The {} community.",
"Step into the light with {}.",
"There's only one true {}!",
"{} rules.",
"{} - Yabba Dabba Duh!",
"Go far with {}.",
"The view on {}.",
"{} for your kids!",
"The {} man.",
"{} is back.",
"{}, there's no better way.",
"There's lots of fun in {}.",
"{} for everybody.",
"{}, to hell with the rest.",
"{} makes your day.",
"{} it's a kind of magic.",
"{} - empowering people.",
"The age of {}.",
"{} - once you have it, you love it.",
"Let your {} flow.",
"Can you feel it? {}.",
"{} is our middle name.",
"Nothing is faster than {}.",
"Food or {}? I'll have {}.",
"The {} way of life.",
"I'd walk a mile for {}.",
"I love {}.",
"{} rocks.",
"{} for your life.",
"{} moments.",
"{} - Xtending service.",
"Do you know {}?",
"{} for everyone.",
"{} - Your personal entertainer.",
"Pure {}. Pure Power.",
"Just {}.",
"{} is rolling, the others are stoned.",
"The goddess made {}.",
"God made {}.",
"Funky {}.",
"Be young, have fun, taste {}.",
"{}, good.",
"hhmmmmm... {}."]
